[Install PyTorch doc](https://pytorch.org/get-started/locally/)

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.11.0+cu126
True
NVIDIA GeForce MX330


1. Tensors represent data in a numerical way

PyTorch tensors are multi-dimensional arrays, similar to NumPy arrays, but with two key advantages: they can run on GPUs for hardware acceleration and are optimized for automatic differentiation (autograd). 


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

In [ ]:
# check dimension
scalar.ndim

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

In [ ]:
# Check the number of dimensions of vector
vector.ndim

In [ ]:
# Check shape of vector
vector.shape

format this to a table please:

Name	What is it?	Number of dimensions	Lower or upper (usually/example)
scalar	a single number	0	Lower (a)
vector	a number with direction (e.g. wind speed with direction) but can also have many other numbers	1	Lower (y)
matrix	a 2-dimensional array of numbers	2	Upper (Q)
tensor	an n-dimensional array of numbers	can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector	Upper (X)

Why use PyTorch:

1. **Speed:**
PyTorch also helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.

So you can focus on manipulating data and writing algorithms and PyTorch will make sure it runs fast.



***Issues***

1. Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [2]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")  # will default to CPU


tensor([[0.1075, 0.3259, 0.4917, 0.9489],
        [0.8858, 0.8998, 0.3384, 0.4314],
        [0.7597, 0.4079, 0.1738, 0.1937]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu



Note: When you run into **issues in PyTorch**, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

> **"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"**

In [3]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [4]:
# Multiply it by 10
tensor * 10


tensor([10, 20, 30])

In [5]:
# Tensors don't change unless reassigned
tensor


tensor([1, 2, 3])

values inside the tensor don't change unless they're reassigned.

In [6]:
# substract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [7]:
# Can also use torch functions
torch.multiply(tensor, 10)


tensor([-90, -80, -70])

In [8]:
# Original tensor is still unchanged
tensor


tensor([-9, -8, -7])

In [9]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)


tensor([-9, -8, -7]) * tensor([-9, -8, -7])
Equals: tensor([81, 64, 49])


## Matrix multiplication (is all you need)¶

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimensions**:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

> Note: "@" in Python is the symbol for matrix multiplication, though not recommended.

In [10]:
tensor = torch.tensor([1, 2, 3])
tensor.shape


torch.Size([3])

The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our `tensor` variable with values `[1, 2, 3]`:

Operation	Calculation	Code
Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	tensor * tensor
Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

In [11]:
# Element-wise matrix multiplication
tensor * tensor


tensor([1, 4, 9])

In [12]:
# Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

## **Shape error in Deep Learning**

In [13]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
print("tensor_A shape:", tensor_A.shape)

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32)
print("\ntensor_B shape:", tensor_B.shape)

torch.matmul(tensor_A, tensor_B)  # (this will error)


tensor_A shape: torch.Size([3, 2])

tensor_B shape: torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [14]:
# Solution =  transpose (switch the dimensions of a given tensor).

# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [15]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [16]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(
    f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n"
)
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [19]:
tensor_A.T

tensor([[1., 3., 5.],
        [2., 4., 6.]])

In [20]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(
    in_features=3,  # in_features = matches inner dimension of input
    out_features=6,
)  # out_features = describes outer value
x = tensor_A.T
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([2, 3])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


## Manipulating Tensors

In [21]:
# Create a tensor
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}")  # won't work without float datatype
print(f"Sum: {x.sum()}")


Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [25]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

Positional min max

In [26]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## **Dtype Error**

In [27]:
# Create a tensor and check its datatype
tensor = torch.arange(10.0, 100.0, 10.0)
tensor.dtype


torch.float32

In [28]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [30]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## **Reproducibility in Randomness**


In [31]:

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B


Tensor A:
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

Tensor B:
tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [32]:
# # Set the random seed
RANDOM_SEED = 42  # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(
    seed=RANDOM_SEED
)  # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## **Getting PyTorch to run on the GPU**

In [33]:
torch.cuda.is_available()


True

In [34]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

> Note: In PyTorch, it's best practice to write device agnostic code. This means code that'll run on CPU (always available) or GPU (if available).



In [35]:
# Count number of devices
torch.cuda.device_count()


1

Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).



In [36]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

In [37]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [38]:
# Instead, copy the tensor back to cpu
# This copies the tensor to CPU memory so it's usable with CPUs.

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

In [39]:
# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises

In [78]:
# 2. Create a random tensor with shape (7, 7).

tensor = torch.rand(size=(7, 7))
tensor, tensor.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

In [42]:
tensor.shape

torch.Size([7, 7])

In [46]:
# 3. Perform a matrix multiplication on the tensor from quesion 2 with another random tensor with shape (1, 7)

tensor_B = torch.rand(1, 7)

torch.matmul(tensor, tensor_B.T)

tensor([[1.9915],
        [1.4538],
        [1.4906],
        [2.0956],
        [2.1863],
        [0.7820],
        [1.9173]])

In [45]:
torch.rand(1, 7).T.shape

torch.Size([7, 1])

In [50]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.

RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
tensor = torch.rand(7, 7)
tensor


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [51]:
# Have to reset the seed every time a new rand() is called
torch.random.manual_seed(seed=RANDOM_SEED)

tensor_B = torch.rand(1, 7)

torch.matmul(tensor, tensor_B.T)


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [52]:
tensor_B

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [79]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(1234)

In [81]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)

tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [83]:
# 7. Perform a matrix multiplication on the tensors you created in 6

tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [62]:
# 8. Find the maximum and minimum values of the output of 7.

print("Max value = ", torch.max(tensor_C))
print("Min value = ", torch.min(tensor_C))

Max value =  tensor(0.6287, device='cuda:0')
Min value =  tensor(0.2161, device='cuda:0')


In [63]:
# 9. Find the maximum and minimum index values of the output of 7.


print("Max Index = ", torch.argmax(tensor_C))
print("Min Index = ", torch.argmin(tensor_C))

Max Index =  tensor(3, device='cuda:0')
Min Index =  tensor(1, device='cuda:0')


In [ ]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and 
# then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and 
# print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)
tensor_D = torch.rand(size=(1, 1, 1, 10))
tensor_D

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [84]:
# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


In [76]:
tensor_E = tensor_D[0][0][0]
tensor_E

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])