
---

# 🎯 Classwork: Customer Purchase Tensor Analysis

You're working as an ML Engineer.
You receive **customer purchase data** and must analyze it using **PyTorch tensors**.

This exercise will make you practice:

* Creating tensors
* Tensor shapes
* Broadcasting
* CPU vs GPU
* Tensor operations

---

# 🧠 Scenario

You are given:

Each row = Customer
Each column = Product Category

| Customer | Food | Electronics | Clothing |
| -------- | ---- | ----------- | -------- |
| A        | 200  | 500         | 100      |
| B        | 150  | 200         | 80       |
| C        | 300  | 100         | 120      |
| D        | 50   | 400         | 60       |

---

# 🧪 Your Tasks

## Task 1 — Create Tensor

Create a PyTorch tensor representing this dataset

Expected Shape:

```
(4 customers, 3 categories)
```

Your goal:

* Import torch
* Create tensor
* Print tensor
* Print shape

---


In [ ]:
import torch

In [ ]:
X = torch.tensor(
    [[200, 500, 100], [150, 200, 80], [300, 100, 120], [50, 400, 60]],
    dtype=torch.float32,
)
print(type(X))
print(X)

<class 'torch.Tensor'>
tensor([[200, 500, 100],
        [150, 200,  80],
        [300, 100, 120],
        [ 50, 400,  60]])


In [ ]:
X.ndim


2


## Task 2 — Tensor Shape Understanding

Print:

* Shape
* Number of dimensions
* Number of elements

You should learn:

```
tensor.shape
tensor.ndim
tensor.numel()
```

In [4]:
print(X.shape)
print(X.ndim)
print(X.numel())

torch.Size([4, 3])
2
12



---

## Task 3 — Tensor Operations

Compute:

### 1. Total spending per customer

Expected output:

```
[800, 430, 520, 510]
```

Hint:

```
sum(dim=?)
```

Think:

* Rows = customers
* So sum across columns


In [ ]:
# dim=1 → sum across columns → per customer
torch.sum(X, dim=1)


tensor([800, 430, 520, 510])


---

### 2. Total spending per category

Expected output:

```
Food total
Electronics total
Clothing total
```

Hint:

```
sum(dim=?)
```

In [6]:
X

tensor([[200, 500, 100],
        [150, 200,  80],
        [300, 100, 120],
        [ 50, 400,  60]])

In [ ]:
# dim=0 → sum across rows → per category
torch.sum(X, dim=0)

tensor([ 700, 1200,  360])



---

## Task 4 — Broadcasting (Very Important)

Suppose:

Company increases **all prices by 10%**

Create:

```
price_multiplier = 1.10
```

Multiply entire tensor

This teaches **broadcasting**

---

Then try:

Give **different category multipliers**

```
Food → +10%
Electronics → +20%
Clothing → +5%
```

Hint:

Create:

```
[1.1, 1.2, 1.05]
```

Then multiply tensor

This is **real broadcasting use case**


In [ ]:
price_multiplier = 1.10  # PyTorch automatically broadcasts scalars.

X * price_multiplier


tensor([[220., 550., 110.],
        [165., 220.,  88.],
        [330., 110., 132.],
        [ 55., 440.,  66.]])

In [10]:
category_increase = torch.tensor([1.10, 1.20, 1.05])

X * category_increase

tensor([[220.0000, 600.0000, 105.0000],
        [165.0000, 240.0000,  84.0000],
        [330.0000, 120.0000, 126.0000],
        [ 55.0000, 480.0000,  63.0000]])


---

# Task 5 — CPU vs GPU

Check:

```
torch.cuda.is_available()
```

Then:

Move tensor to GPU

```
tensor.to("cuda")
```

Print:

```
tensor.device
```

This is **real-world PyTorch skill**


In [11]:
torch.cuda.is_available()

True

In [12]:
X.device

device(type='cpu')

In [19]:
X=X.to("cuda")
X.device

device(type='cuda', index=0)


---

# Task 6 — Real ML Engineer Task

Find:

### Top spending customer

Hint:

```
torch.argmax()
```

In [20]:
X

tensor([[200, 500, 100],
        [150, 200,  80],
        [300, 100, 120],
        [ 50, 400,  60]], device='cuda:0')

In [22]:
customer_totals = X.sum(dim=1)

torch.argmax(customer_totals)

tensor(0, device='cuda:0')

In [23]:
top_customer = torch.argmax(customer_totals)

X[top_customer]


tensor([200, 500, 100], device='cuda:0')


---

### Customer with lowest spending

Hint:

```
torch.argmin()
```

In [24]:
lowest_customer = torch.argmin(customer_totals)
print("Lowest customer index:", lowest_customer)


Lowest customer index: tensor(1, device='cuda:0')


In [25]:
X[lowest_customer]

tensor([150, 200,  80], device='cuda:0')




---

# Expected Learning After This

After this exercise, you'll understand:

✔ Tensor creation
✔ Shapes
✔ Broadcasting
✔ GPU usage
✔ Tensor operations

This is **exactly what real ML engineers use daily**

---



# Your Tensor

```python
X = torch.tensor([
    [200, 500, 100],   # Customer A
    [150, 200, 80],    # Customer B
    [300, 100, 120],   # Customer C
    [50, 400, 60]      # Customer D
])
```

Let's label it:

| Customer | Food | Electronics | Clothing |
| -------- | ---- | ----------- | -------- |
| A        | 200  | 500         | 100      |
| B        | 150  | 200         | 80       |
| C        | 300  | 100         | 120      |
| D        | 50   | 400         | 60       |

---

# Very Important Rule

In PyTorch:

```
dim=0 → down (rows)
dim=1 → across (columns)
```

Think:

```
dim=0  (vertical ↓)

dim=1  (horizontal →)
```

---

# Shape

```python
X.shape
```

Result:

```
(4, 3)
```

Meaning:

* 4 rows (customers)
* 3 columns (categories)

So:

```
dim=0 → 4 (customers)
dim=1 → 3 (categories)
```

---

# When You Do

```python
torch.sum(X, dim=1)
```

You're saying:

**"Sum across columns" (horizontal)**

So:

Customer A:

```
[200, 500, 100]
```

Sum:

```
200 + 500 + 100 = 800
```

Customer B:

```
[150, 200, 80]
```

Sum:

```
430
```

So result:

```
[800, 430, 520, 510]
```

This is **per customer**.

Because **each row = customer**

---

# When You Do

```python
torch.sum(X, dim=0)
```

You're saying:

**"Sum down rows" (vertical)**

Food column:

```
[200,
 150,
 300,
 50]
```

Sum:

```
700
```

Electronics:

```
[500,
 200,
 100,
 400]
```

Sum:

```
1200
```

Clothing:

```
[100,
 80,
 120,
 60]
```

Sum:

```
360
```

Result:

```
[700, 1200, 360]
```

---

# The Mental Model That Never Fails

Think:

```
dim=0 → vertical operation
dim=1 → horizontal operation
```

---

# Visual Memory Trick

Imagine this:

```
dim=1 → ← →  (across rows)

dim=0 → ↑ ↓  (down columns)
```

---
